// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: proto/trafficLights.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "trafficLights";

export interface UpdateTrafficLightDto {
  id: string;
  name: string;
  location: string;
  mode: string;
}

export interface FindOneTrafficLightDto {
  id: string;
}

export interface Empty {
}

export interface TrafficLights {
  trafficLights: TrafficLight[];
}

export interface CreateTrafficLightDto {
  name: string;
  location: string;
  mode: string;
}

export interface TrafficLight {
  id: string;
  name: string;
  location: string;
  mode: string;
}

export const TRAFFIC_LIGHTS_PACKAGE_NAME = "trafficLights";

export interface TrafficLightsServiceClient {
  createTrafficLight(request: CreateTrafficLightDto): Observable<TrafficLight>;

  findAllTrafficLights(request: Empty): Observable<TrafficLights>;

  findOneTrafficLight(request: FindOneTrafficLightDto): Observable<TrafficLight>;

  updateTrafficLight(request: UpdateTrafficLightDto): Observable<TrafficLight>;

  removeTrafficLight(request: FindOneTrafficLightDto): Observable<TrafficLight>;
}

export interface TrafficLightsServiceController {
  createTrafficLight(request: CreateTrafficLightDto): Promise<TrafficLight> | Observable<TrafficLight> | TrafficLight;

  findAllTrafficLights(request: Empty): Promise<TrafficLights> | Observable<TrafficLights> | TrafficLights;

  findOneTrafficLight(request: FindOneTrafficLightDto): Promise<TrafficLight> | Observable<TrafficLight> | TrafficLight;

  updateTrafficLight(request: UpdateTrafficLightDto): Promise<TrafficLight> | Observable<TrafficLight> | TrafficLight;

  removeTrafficLight(request: FindOneTrafficLightDto): Promise<TrafficLight> | Observable<TrafficLight> | TrafficLight;
}

export function TrafficLightsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createTrafficLight",
      "findAllTrafficLights",
      "findOneTrafficLight",
      "updateTrafficLight",
      "removeTrafficLight",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TrafficLightsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TrafficLightsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TRAFFIC_LIGHTS_SERVICE_NAME = "TrafficLightsService";
