services:
  gateway:
    build:
      context: ./mvts-api-gateway
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./mvts-api-gateway/.env
    networks:
      - frontend
      - backend
  cars-manager:
    container_name: cars-manager
    build:
      context: ./mvts-cars-manager
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./mvts-cars-manager/.env
    ports:
      - '5001:5000'
    depends_on:
      - db
      - rmq
    networks:
      - backend
  traffic-lights-manager:
    container_name: traffic-lights-manager
    build:
      context: ./mvts-traffic-lights-manager
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./mvts-traffic-lights-manager/.env
    depends_on:
      - db
      - rmq
    ports:
      - '5002:5000'
    networks:
      - backend
  db:
    image: postgres
    container_name: db
    restart: always
    # set shared memory limit when using docker compose
    # shm_size: 128mb
    ports:
      - '5432:5432'
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_MULTIPLE_DATABASES: mvts_traffic_lights_db, mvts_car_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    # env_file:
    #   - ./postgres/.env
  rmq:
    image: rabbitmq:3-management
    container_name: rmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - backend
volumes:
  postgres_data:

networks:
  frontend:
  backend:
