import type { Cart } from '@/types/Cart';

export const testCart: Cart[] = [
    {
        id: 1,
        name: "Carrito A",
        state: "Nuevo",
        type: "Transporte",
        capacity: "500kg",
        material: "Acero",
        quantity: "2",
        departure: "Madrid",
        destination: "Barcelona",
        departureTime: "2025-06-01T08:00:00",
        arrivalTime: "2025-06-01T12:00:00",
    },
    {
        id: 2,
        name: "Carrito B",
        state: "Usado",
        type: "Carga",
        capacity: "300kg",
        material: "Aluminio",
        quantity: "3",
        departure: "Valencia",
        destination: "Sevilla",
        departureTime: "2025-06-02T09:00:00",
        arrivalTime: "2025-06-02T13:00:00",
    },
    {
        id: 3,
        name: "Carrito C",
        state: "Nuevo",
        type: "Carga",
        capacity: "200kg",
        material: "Plástico",
        quantity: "1",
        departure: "Madrid",
        destination: "Bilbao",
        departureTime: "2025-06-03T10:00:00",
        arrivalTime: "2025-06-03T14:00:00",
    },
    {
        id: 4,
        name: "Carrito D",
        state: "Usado",
        type: "Transporte",
        capacity: "400kg",
        material: "Acero inoxidable",
        quantity: "5",
        departure: "Zaragoza",
        destination: "Granada",
        departureTime: "2025-06-04T07:30:00",
        arrivalTime: "2025-06-04T11:30:00",
    },
    {
        id: 5,
        name: "Carrito E",
        state: "Nuevo",
        type: "Transporte",
        capacity: "1000kg",
        material: "Fibra de carbono",
        quantity: "4",
        departure: "Málaga",
        destination: "Alicante",
        departureTime: "2025-06-05T11:00:00",
        arrivalTime: "2025-06-05T15:00:00",
    },
];