// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mtvs_shipment_service.Setting;

#nullable disable

namespace mtvs_shipment_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mtvs_shipment_service.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDelivered")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_delivered");

                    b.Property<int>("IdRoute")
                        .HasColumnType("integer")
                        .HasColumnName("id_route");

                    b.Property<int>("IdVehicle")
                        .HasColumnType("integer")
                        .HasColumnName("id_vehicle");

                    b.Property<int>("Material")
                        .HasColumnType("integer")
                        .HasColumnName("material");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
